"""Adicionar modelo Categoria

Revision ID: 15a87dcc035e
Revises: dc82777efdaa
Create Date: 2025-03-19 02:05:23.484416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a87dcc035e'
down_revision = 'dc82777efdaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_produto_categoria', 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint('fk_produto_categoria', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
