"""Alteracao Upload Imagens

Revision ID: f557b7e9826c
Revises: 15a87dcc035e
Create Date: 2025-03-21 13:11:41.093811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f557b7e9826c'
down_revision = '15a87dcc035e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_nome', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('imagem_data', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('imagem_data')
        batch_op.drop_column('imagem_nome')

    # ### end Alembic commands ###
